### ISSUE TITLE
vim 中不知道怎么保存

### ISSUE THREAD

**Issue by fengsanv** [MrEasonYang/flomo-cli#1]
非常好的创意，刚试用了，只是不知道在vim中如何保存？

**Comment by MrEasonYang** [comment]
是说在 vim 中 :wq 后内容没有成功保存到 flomo 吗？

**Comment by fengsanv** [comment]
是的。提示出错。

Eason Yang ***@***.***> 于2021年10月1日周五 19:25写道：

**Comment by fengsanv** [comment]
提示 E212：无法打开并写入文件。vim  8.2的版本。

**Comment by MrEasonYang** [comment]
vim 的这个提示应该是当前用户对目标目录没有权限，请检查当前用户是否拥有 ~/.flomo-tmp 目录的权限

**Comment by fengsanv** [comment]
使用的是administrator账户，从命令行启动vim，可以直接写入文件，使用Gvim也可以保存至目录。挺迷惑的。

Eason Yang ***@***.***> 于2022年1月1日周六 00:42写道：

**Comment by MrEasonYang** [comment]
用 Windows 设备排查了下，发现是临时文件的路径设置在跨平台时存在兼容问题，已在 v1.0.3 中修复 #2
